# Cloudflare Workers配置文件
name = "ccdrop-signaling-server"
main = "src/workers/index.ts"
compatibility_date = "2024-01-01"

# 环境变量配置
[vars]
# 可以在这里定义环境变量

# 路由配置
[[routes]]
pattern = "your-subdomain.workers.dev"
zone_name = "your-domain.com"

# 开发环境配置
[dev]

# 发布环境配置
[env.production]